# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Package Publishing

on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  publish:
    name: Release woundtissueclassification
    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path:
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys:
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradle to Execute
        run: chmod +x gradlew

      - name: Build AAR
        run: bash ./gradlew :woundtissueclassification:assemble


      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: bash ./gradlew :woundtissueclassification:publish
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
